version: "2"

services:

# ------> node ------>
    node_2rlg4bknjlxx7tw2:
        container_name: node_2rlg4bknjlxx7tw2
        image: node:10.5-alpine
        user: "node"
        working_dir: /node
        volumes:
            - .././:/node
        environment:
            NODE_ENV: dev
        expose:
            - 8081
# <------ node <------